// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_id_ from "./routes/(platform)/[id].tsx";
import * as $_platform_layout from "./routes/(platform)/_layout.tsx";
import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_chars from "./routes/(platform)/chars.tsx";
import * as $_platform_favourites from "./routes/(platform)/favourites.tsx";
import * as $_platform_logout_do from "./routes/(platform)/logout/do.tsx";
import * as $_platform_logout_view from "./routes/(platform)/logout/view.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $charCard from "./islands/charCard.tsx";
import * as $charFav from "./islands/charFav.tsx";
import * as $charList from "./islands/charList.tsx";
import * as $formulario from "./islands/formulario.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/[id].tsx": $_platform_id_,
    "./routes/(platform)/_layout.tsx": $_platform_layout,
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/chars.tsx": $_platform_chars,
    "./routes/(platform)/favourites.tsx": $_platform_favourites,
    "./routes/(platform)/logout/do.tsx": $_platform_logout_do,
    "./routes/(platform)/logout/view.tsx": $_platform_logout_view,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/charCard.tsx": $charCard,
    "./islands/charFav.tsx": $charFav,
    "./islands/charList.tsx": $charList,
    "./islands/formulario.tsx": $formulario,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
